name: Build

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v4

      - name: Install LLVM.
        run: choco install llvm -y

      - name: Bootstrap compiler.
        run: make bootstrap

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: zirconc-windows-amd64
          path: bin/zirconc.exe
