name: Build

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v4

      - name: Install LLVM.
        run: choco install llvm -y

      - name: Build compiler.
        shell: cmd
        run: |
          ren zirconc.exe old_zirconc.exe
          old_zirconc.exe main -O0 -L "C:\Program Files\LLVM\lib" -lLLVM-C -o zirconc.exe -g

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: zirconc-windows-amd64
          path: zirconc.exe