name: Build

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v4

      - name: Install LLVM.
        run: choco install llvm -y

      - name: Build compiler.
        shell: cmd
        run: |
          ren divinec.exe old_divinec.exe
          old_divinec.exe main.div -O0 -L "C:\Program Files\LLVM\lib" -lLLVM-C -o divinec.exe -g

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: divinec-windows-amd64
          path: divinec.exe